version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kumaaraso
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./server/database/mysql-data/:/var/lib/mysql
      - ./server/database/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./kumaaraso-radio-client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      app:
        condition: service_started
        restart: true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      mysql: 
        condition: service_healthy
        restart: true
      app:
        condition: service_started
        restart: true
      frontend:
        condition: service_started
        restart: true
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge