CREATE DATABASE IF NOT EXISTS kumaaraso;
USE kumaaraso;

CREATE TABLE IF NOT EXISTS audio (
  id INT PRIMARY KEY AUTO_INCREMENT,
  call_id VARCHAR(512),
  path VARCHAR(512)
);


CREATE TABLE IF NOT EXISTS radio (
  id INT PRIMARY KEY AUTO_INCREMENT,
  file_id VARCHAR(512),
  path VARCHAR(512)
);
